server:
  port: 9000
spring:
  application:
    name: wavetop-eureka # ????????????????????eureka??????

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: false
    fetch-registry: false